module.exports = {
    name: "deep",
    description: "Deep command",
    execute(message, args)  {

const deep_quotes = [
        "¿Cómo podemos ser reales los espejos si nuestros ojos no lo son?",
        "Es cierto que no sabemos lo que tenemos hasta que lo perdemos, pero también es cierto que no sabemos lo que tenemos estado perdiendo hasta que lo tengamos.",
        "Mañana es el primer día del resto de tu vida",
        "Las similitudes entre mi padre y yo son diferentes",
        "Juego al fútbol. No estoy tratando de ser un profesor. Las pruebas no parecen tener sentido para mí, midiendo tu cerebro en cosas que no he pasado en la escuela",
        "Me graduaré a tiempo, sin importar cuánto tiempo tome",
        "Si hiciera eso, estaría metiendo la cabeza en un alce",
        "Fumar mata, y si te matan, has perdido una parte muy importante de tu vida",
        "¡¿Quién en su sano juicio necesitaría más de 640k de ram ?! - Bill Gates 1981",
        "La mujer promedio preferiría tener belleza que cerebro, porque el hombre promedio puede ver mejor de lo que puede pensar",
        "Una de las mejores cosas de los libros es que a veces hay imágenes fantásticas",
        "Recuerda siempre: eres único, como todos los demás",
        "El camino hacia el éxito siempre está en construcción",
        "Cuando todo viene en camino, estás en el carril equivocado",
        "Todos quieren ir al cielo, pero nadie quiere morir",
        "El que rió último, no lo entendió",
        "La mitad de las personas en el mundo están por debajo del promedio",
        "Chuck Norris frecuentemente dona sangre a la Cruz Roja. Simplemente nunca la suya",
        "La mediana edad es cuando tu edad comienza a mostrarse alrededor de tu media",
        "Soy tan inteligente que a veces no entiendo una sola palabra de lo que digo",
        "Cuando se trata de pensar, algunas personas no se detienen ante nada",
        "La felicidad es tener una familia grande, amorosa, cariñosa y unida en otra ciudad",
        "No me digas que el cielo es el límite cuando hay huellas en la luna",
        "Hago suficiente ejercicio empujando mi suerte",
        "Cuanta más gente conozco, más me gusta mi perro",
        "Hay tres tipos de personas en este mundo: los que pueden contar y los que no",
        "Cuando la vida te da limones, haz limonada, encuentra a la persona a quien la vida le dio vodka y haz una fiesta",
        "Dios creó el mundo, todo lo demás está hecho en China",
        "Antes de criticar a alguien, camine una milla en sus zapatos. De esa manera, estará a una milla de ellos y tendrá sus zapatos",
        "Nunca entiendes realmente algo a menos que puedas explicárselo a tu abuela",
        "Error. Sin teclado. Presione F1 para continuar",
        "La experiencia es lo que obtienes cuando no obtienes lo que querías",
        "La vida es como una carrera, ganes o pierdas, quedes en el puesto que quedes esta va a acabar.",
        "El cambio es bueno, pero los dólares son mejores",
        "Solución a dos de los problemas del mundo: alimentar a las personas sin hogar a los hambrientos",
        "Cuando la vida te da melones ... podrías ser disléxico",
        "¡Los que critican a nuestra generación parecen olvidar quién la crió!",
        "¡Los niños en el asiento trasero causan accidentes, los accidentes en el asiento trasero causan niños!",
        "¿Cómo sabes cuándo estás demasiado borracho para conducir? Cuando giras para no chocar con un árbol ... y luego te das cuenta de que era tu ambientador",
        "Alcohol, ¿qué es eso? No está en mi vodkabulary, pero déjame comprobar en whiskypedia",
        "Juro solemnemente que no estoy haciendo nada bueno.",
        "Una manzana al día mantiene a cualquiera de todos modos, si la tiras lo suficientemente fuerte",
        "Cuando mi jefe me preguntó quién era el estúpido, ¿él o él? Le dije que todo el mundo sabe que no contrata gente estúpida",
        "No importa cuán inteligente seas, nunca puedes convencer a alguien estúpido de que es estúpido",
        "Un policía me detuvo y me dijo Papeles, así que dije ¡Tijeras, yo gano! Y me fui",
        "Si crees que tu jefe es estúpido, recuerda: no tendrías un trabajo si fuera más listo",
        "¿Cómo pueden oler mis pies si no tienen nariz?",
        "Una persona estúpida se ríe tres veces de un chiste; una vez cuando todos los demás se ríen, una segunda vez cuando realmente entiende el chiste, y una tercera vez cuando se da cuenta de que se estaba riendo sin entender el chiste al principio",
        "No tropecé y caí. Ataqué el piso y creo que estoy ganando",
        "Puedes dejar de volverme loco, puedo caminar desde aquí",
        "El brócoli dice 'Me veo como un árbol pequeño', el hongo dice 'Me veo como un paraguas', la nuez dice 'Me veo como un cerebro', y el plátano dice '¿Podemos cambiar de tema?'",
        "Sé que soy estúpido pero cuando miro a mi alrededor me siento mucho mejor",
        "Nunca me disculpo. Lo siento, pero así es como soy ...",
        "Puse mi teléfono en modo avión, ¡pero no está volando!",
        "Hoy fui un héroe. Rescaté un poco de cerveza que estaba atrapada en una botella",
        "Con gran potencia viene una factura de electricidad aún mayor",
        "Una computadora una vez me ganó en el ajedrez, pero no fue rival para mí en el kick boxing."
];

    let index = Math.floor(Math.random() * (deep_quotes.length))
    message.channel.send(deep_quotes[index])
}};